package unidue.rc.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.PermissionDefinition;
import unidue.rc.model.Role;

/**
 * Class _Action was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Action extends CayenneDataObject {

    public static final String ATTRIBUTE_PROPERTY = "attribute";
    public static final String NAME_PROPERTY = "name";
    public static final String RESOURCE_PROPERTY = "resource";
    public static final String PERMISSION_DEFINITIONS_PROPERTY = "permissionDefinitions";
    public static final String ROLES_PROPERTY = "roles";

    public static final String ID_PK_COLUMN = "id";

    public void setAttribute(String attribute) {
        writeProperty(ATTRIBUTE_PROPERTY, attribute);
    }
    public String getAttribute() {
        return (String)readProperty(ATTRIBUTE_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setResource(String resource) {
        writeProperty(RESOURCE_PROPERTY, resource);
    }
    public String getResource() {
        return (String)readProperty(RESOURCE_PROPERTY);
    }

    public void addToPermissionDefinitions(PermissionDefinition obj) {
        addToManyTarget(PERMISSION_DEFINITIONS_PROPERTY, obj, true);
    }
    public void removeFromPermissionDefinitions(PermissionDefinition obj) {
        removeToManyTarget(PERMISSION_DEFINITIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PermissionDefinition> getPermissionDefinitions() {
        return (List<PermissionDefinition>)readProperty(PERMISSION_DEFINITIONS_PROPERTY);
    }


    public void addToRoles(Role obj) {
        addToManyTarget(ROLES_PROPERTY, obj, true);
    }
    public void removeFromRoles(Role obj) {
        removeToManyTarget(ROLES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Role> getRoles() {
        return (List<Role>)readProperty(ROLES_PROPERTY);
    }


}
