package unidue.rc.model.auto;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Entry;
import unidue.rc.model.Resource;
import unidue.rc.model.ScanJob;

/**
 * Class _BookChapter was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BookChapter extends CayenneDataObject {

    public static final String BOOK_AUTHORS_PROPERTY = "bookAuthors";
    public static final String BOOK_TITLE_PROPERTY = "bookTitle";
    public static final String CHAPTER_AUTHORS_PROPERTY = "chapterAuthors";
    public static final String CHAPTER_TITLE_PROPERTY = "chapterTitle";
    public static final String COMMENT_PROPERTY = "comment";
    public static final String EDITION_PROPERTY = "edition";
    public static final String EDITOR_PROPERTY = "editor";
    public static final String ISBN_PROPERTY = "isbn";
    public static final String PAGE_END_PROPERTY = "pageEnd";
    public static final String PAGE_START_PROPERTY = "pageStart";
    public static final String PLACE_OF_PUBLICATION_PROPERTY = "placeOfPublication";
    public static final String PUBLISHER_PROPERTY = "publisher";
    public static final String REFERENCE_NUMBER_PROPERTY = "referenceNumber";
    public static final String SIGNATURE_PROPERTY = "signature";
    public static final String YEAR_OF_PUBLICATION_PROPERTY = "yearOfPublication";
    public static final String ENTRY_PROPERTY = "entry";
    public static final String RESOURCE_PROPERTY = "resource";
    public static final String SCAN_JOB_PROPERTY = "scanJob";

    public static final String ID_PK_COLUMN = "id";

    public void setBookAuthors(String bookAuthors) {
        writeProperty(BOOK_AUTHORS_PROPERTY, bookAuthors);
    }
    public String getBookAuthors() {
        return (String)readProperty(BOOK_AUTHORS_PROPERTY);
    }

    public void setBookTitle(String bookTitle) {
        writeProperty(BOOK_TITLE_PROPERTY, bookTitle);
    }
    public String getBookTitle() {
        return (String)readProperty(BOOK_TITLE_PROPERTY);
    }

    public void setChapterAuthors(String chapterAuthors) {
        writeProperty(CHAPTER_AUTHORS_PROPERTY, chapterAuthors);
    }
    public String getChapterAuthors() {
        return (String)readProperty(CHAPTER_AUTHORS_PROPERTY);
    }

    public void setChapterTitle(String chapterTitle) {
        writeProperty(CHAPTER_TITLE_PROPERTY, chapterTitle);
    }
    public String getChapterTitle() {
        return (String)readProperty(CHAPTER_TITLE_PROPERTY);
    }

    public void setComment(String comment) {
        writeProperty(COMMENT_PROPERTY, comment);
    }
    public String getComment() {
        return (String)readProperty(COMMENT_PROPERTY);
    }

    public void setEdition(String edition) {
        writeProperty(EDITION_PROPERTY, edition);
    }
    public String getEdition() {
        return (String)readProperty(EDITION_PROPERTY);
    }

    public void setEditor(String editor) {
        writeProperty(EDITOR_PROPERTY, editor);
    }
    public String getEditor() {
        return (String)readProperty(EDITOR_PROPERTY);
    }

    public void setIsbn(String isbn) {
        writeProperty(ISBN_PROPERTY, isbn);
    }
    public String getIsbn() {
        return (String)readProperty(ISBN_PROPERTY);
    }

    public void setPageEnd(String pageEnd) {
        writeProperty(PAGE_END_PROPERTY, pageEnd);
    }
    public String getPageEnd() {
        return (String)readProperty(PAGE_END_PROPERTY);
    }

    public void setPageStart(String pageStart) {
        writeProperty(PAGE_START_PROPERTY, pageStart);
    }
    public String getPageStart() {
        return (String)readProperty(PAGE_START_PROPERTY);
    }

    public void setPlaceOfPublication(String placeOfPublication) {
        writeProperty(PLACE_OF_PUBLICATION_PROPERTY, placeOfPublication);
    }
    public String getPlaceOfPublication() {
        return (String)readProperty(PLACE_OF_PUBLICATION_PROPERTY);
    }

    public void setPublisher(String publisher) {
        writeProperty(PUBLISHER_PROPERTY, publisher);
    }
    public String getPublisher() {
        return (String)readProperty(PUBLISHER_PROPERTY);
    }

    public void setReferenceNumber(String referenceNumber) {
        writeProperty(REFERENCE_NUMBER_PROPERTY, referenceNumber);
    }
    public String getReferenceNumber() {
        return (String)readProperty(REFERENCE_NUMBER_PROPERTY);
    }

    public void setSignature(String signature) {
        writeProperty(SIGNATURE_PROPERTY, signature);
    }
    public String getSignature() {
        return (String)readProperty(SIGNATURE_PROPERTY);
    }

    public void setYearOfPublication(Integer yearOfPublication) {
        writeProperty(YEAR_OF_PUBLICATION_PROPERTY, yearOfPublication);
    }
    public Integer getYearOfPublication() {
        return (Integer)readProperty(YEAR_OF_PUBLICATION_PROPERTY);
    }

    public void setEntry(Entry entry) {
        setToOneTarget(ENTRY_PROPERTY, entry, true);
    }

    public Entry getEntry() {
        return (Entry)readProperty(ENTRY_PROPERTY);
    }


    public void setResource(Resource resource) {
        setToOneTarget(RESOURCE_PROPERTY, resource, true);
    }

    public Resource getResource() {
        return (Resource)readProperty(RESOURCE_PROPERTY);
    }


    public void setScanJob(ScanJob scanJob) {
        setToOneTarget(SCAN_JOB_PROPERTY, scanJob, true);
    }

    public ScanJob getScanJob() {
        return (ScanJob)readProperty(SCAN_JOB_PROPERTY);
    }


}
