package unidue.rc.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Book;
import unidue.rc.model.BookJobStatus;
import unidue.rc.model.JobComment;

/**
 * Class _BookJob was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BookJob extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String STATUS_PROPERTY = "status";
    public static final String BOOK_PROPERTY = "book";
    public static final String COMMENTS_PROPERTY = "comments";

    public static final String ID_PK_COLUMN = "id";

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setStatus(BookJobStatus status) {
        writeProperty(STATUS_PROPERTY, status);
    }
    public BookJobStatus getStatus() {
        return (BookJobStatus)readProperty(STATUS_PROPERTY);
    }

    public void setBook(Book book) {
        setToOneTarget(BOOK_PROPERTY, book, true);
    }

    public Book getBook() {
        return (Book)readProperty(BOOK_PROPERTY);
    }


    public void addToComments(JobComment obj) {
        addToManyTarget(COMMENTS_PROPERTY, obj, true);
    }
    public void removeFromComments(JobComment obj) {
        removeToManyTarget(COMMENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<JobComment> getComments() {
        return (List<JobComment>)readProperty(COMMENTS_PROPERTY);
    }


}
