package unidue.rc.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.BookJob;
import unidue.rc.model.BookingStatus;
import unidue.rc.model.Entry;
import unidue.rc.model.Resource;

/**
 * Class _Book was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Book extends CayenneDataObject {

    public static final String AUTHORS_PROPERTY = "authors";
    public static final String BOOKING_STATUS_PROPERTY = "bookingStatus";
    public static final String COLLECTION_NUMBER_PROPERTY = "collectionNumber";
    public static final String COMMENT_PROPERTY = "comment";
    public static final String EDITION_PROPERTY = "edition";
    public static final String ISBN_PROPERTY = "isbn";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String PLACE_OF_PUBLICATION_PROPERTY = "placeOfPublication";
    public static final String PUBLISHER_PROPERTY = "publisher";
    public static final String RESOURCE_TYPE_PROPERTY = "resourceType";
    public static final String SIGNATURE_PROPERTY = "signature";
    public static final String THUMBNAIL_URL_PROPERTY = "thumbnailURL";
    public static final String TITLE_PROPERTY = "title";
    public static final String VOLUME_PROPERTY = "volume";
    public static final String YEAR_OF_PUBLICATION_PROPERTY = "yearOfPublication";
    public static final String BOOK_JOB_PROPERTY = "bookJob";
    public static final String ENTRY_PROPERTY = "entry";
    public static final String RESOURCE_PROPERTY = "resource";

    public static final String ID_PK_COLUMN = "id";

    public void setAuthors(String authors) {
        writeProperty(AUTHORS_PROPERTY, authors);
    }
    public String getAuthors() {
        return (String)readProperty(AUTHORS_PROPERTY);
    }

    public void setBookingStatus(BookingStatus bookingStatus) {
        writeProperty(BOOKING_STATUS_PROPERTY, bookingStatus);
    }
    public BookingStatus getBookingStatus() {
        return (BookingStatus)readProperty(BOOKING_STATUS_PROPERTY);
    }

    public void setCollectionNumber(String collectionNumber) {
        writeProperty(COLLECTION_NUMBER_PROPERTY, collectionNumber);
    }
    public String getCollectionNumber() {
        return (String)readProperty(COLLECTION_NUMBER_PROPERTY);
    }

    public void setComment(String comment) {
        writeProperty(COMMENT_PROPERTY, comment);
    }
    public String getComment() {
        return (String)readProperty(COMMENT_PROPERTY);
    }

    public void setEdition(String edition) {
        writeProperty(EDITION_PROPERTY, edition);
    }
    public String getEdition() {
        return (String)readProperty(EDITION_PROPERTY);
    }

    public void setIsbn(String isbn) {
        writeProperty(ISBN_PROPERTY, isbn);
    }
    public String getIsbn() {
        return (String)readProperty(ISBN_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setPlaceOfPublication(String placeOfPublication) {
        writeProperty(PLACE_OF_PUBLICATION_PROPERTY, placeOfPublication);
    }
    public String getPlaceOfPublication() {
        return (String)readProperty(PLACE_OF_PUBLICATION_PROPERTY);
    }

    public void setPublisher(String publisher) {
        writeProperty(PUBLISHER_PROPERTY, publisher);
    }
    public String getPublisher() {
        return (String)readProperty(PUBLISHER_PROPERTY);
    }

    public void setResourceType(String resourceType) {
        writeProperty(RESOURCE_TYPE_PROPERTY, resourceType);
    }
    public String getResourceType() {
        return (String)readProperty(RESOURCE_TYPE_PROPERTY);
    }

    public void setSignature(String signature) {
        writeProperty(SIGNATURE_PROPERTY, signature);
    }
    public String getSignature() {
        return (String)readProperty(SIGNATURE_PROPERTY);
    }

    public void setThumbnailURL(String thumbnailURL) {
        writeProperty(THUMBNAIL_URL_PROPERTY, thumbnailURL);
    }
    public String getThumbnailURL() {
        return (String)readProperty(THUMBNAIL_URL_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void setVolume(String volume) {
        writeProperty(VOLUME_PROPERTY, volume);
    }
    public String getVolume() {
        return (String)readProperty(VOLUME_PROPERTY);
    }

    public void setYearOfPublication(Integer yearOfPublication) {
        writeProperty(YEAR_OF_PUBLICATION_PROPERTY, yearOfPublication);
    }
    public Integer getYearOfPublication() {
        return (Integer)readProperty(YEAR_OF_PUBLICATION_PROPERTY);
    }

    public void setBookJob(BookJob bookJob) {
        setToOneTarget(BOOK_JOB_PROPERTY, bookJob, true);
    }

    public BookJob getBookJob() {
        return (BookJob)readProperty(BOOK_JOB_PROPERTY);
    }


    public void setEntry(Entry entry) {
        setToOneTarget(ENTRY_PROPERTY, entry, true);
    }

    public Entry getEntry() {
        return (Entry)readProperty(ENTRY_PROPERTY);
    }


    public void setResource(Resource resource) {
        setToOneTarget(RESOURCE_PROPERTY, resource, true);
    }

    public Resource getResource() {
        return (Resource)readProperty(RESOURCE_PROPERTY);
    }


}
