package unidue.rc.model.auto;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Department;

/**
 * Class _Department was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Department extends CayenneDataObject {

    public static final String CATEGORY_ID_PROPERTY = "categoryId";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String LANG_PROPERTY = "lang";
    public static final String PARENT_ID_PROPERTY = "parentId";
    public static final String TEXT_PROPERTY = "text";
    public static final String PARENT_PROPERTY = "parent";

    public static final String DEPARTMENT_ID_PK_COLUMN = "departmentId";

    public void setCategoryId(String categoryId) {
        writeProperty(CATEGORY_ID_PROPERTY, categoryId);
    }
    public String getCategoryId() {
        return (String)readProperty(CATEGORY_ID_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setLang(String lang) {
        writeProperty(LANG_PROPERTY, lang);
    }
    public String getLang() {
        return (String)readProperty(LANG_PROPERTY);
    }

    public void setParentId(Integer parentId) {
        writeProperty(PARENT_ID_PROPERTY, parentId);
    }
    public Integer getParentId() {
        return (Integer)readProperty(PARENT_ID_PROPERTY);
    }

    public void setText(String text) {
        writeProperty(TEXT_PROPERTY, text);
    }
    public String getText() {
        return (String)readProperty(TEXT_PROPERTY);
    }

    public void setParent(Department parent) {
        setToOneTarget(PARENT_PROPERTY, parent, true);
    }

    public Department getParent() {
        return (Department)readProperty(PARENT_PROPERTY);
    }


}
