package unidue.rc.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Book;
import unidue.rc.model.BookChapter;
import unidue.rc.model.File;
import unidue.rc.model.Headline;
import unidue.rc.model.Html;
import unidue.rc.model.JournalArticle;
import unidue.rc.model.Reference;
import unidue.rc.model.ReserveCollection;
import unidue.rc.model.WebLink;

/**
 * Class _Entry was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Entry extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String DELETED_PROPERTY = "deleted";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String POSITION_PROPERTY = "position";
    public static final String BOOK_PROPERTY = "book";
    public static final String BOOK_CHAPTER_PROPERTY = "bookChapter";
    public static final String FILE_PROPERTY = "file";
    public static final String HEADLINE_PROPERTY = "headline";
    public static final String HTML_PROPERTY = "html";
    public static final String JOURNAL_ARTICLE_PROPERTY = "journalArticle";
    public static final String REFERENCE_PROPERTY = "reference";
    public static final String RESERVE_COLLECTION_PROPERTY = "reserveCollection";
    public static final String WEB_LINK_PROPERTY = "webLink";

    public static final String ID_PK_COLUMN = "id";

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setDeleted(Date deleted) {
        writeProperty(DELETED_PROPERTY, deleted);
    }
    public Date getDeleted() {
        return (Date)readProperty(DELETED_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setPosition(Integer position) {
        writeProperty(POSITION_PROPERTY, position);
    }
    public Integer getPosition() {
        return (Integer)readProperty(POSITION_PROPERTY);
    }

    public void setBook(Book book) {
        setToOneTarget(BOOK_PROPERTY, book, true);
    }

    public Book getBook() {
        return (Book)readProperty(BOOK_PROPERTY);
    }


    public void setBookChapter(BookChapter bookChapter) {
        setToOneTarget(BOOK_CHAPTER_PROPERTY, bookChapter, true);
    }

    public BookChapter getBookChapter() {
        return (BookChapter)readProperty(BOOK_CHAPTER_PROPERTY);
    }


    public void setFile(File file) {
        setToOneTarget(FILE_PROPERTY, file, true);
    }

    public File getFile() {
        return (File)readProperty(FILE_PROPERTY);
    }


    public void setHeadline(Headline headline) {
        setToOneTarget(HEADLINE_PROPERTY, headline, true);
    }

    public Headline getHeadline() {
        return (Headline)readProperty(HEADLINE_PROPERTY);
    }


    public void setHtml(Html html) {
        setToOneTarget(HTML_PROPERTY, html, true);
    }

    public Html getHtml() {
        return (Html)readProperty(HTML_PROPERTY);
    }


    public void setJournalArticle(JournalArticle journalArticle) {
        setToOneTarget(JOURNAL_ARTICLE_PROPERTY, journalArticle, true);
    }

    public JournalArticle getJournalArticle() {
        return (JournalArticle)readProperty(JOURNAL_ARTICLE_PROPERTY);
    }


    public void setReference(Reference reference) {
        setToOneTarget(REFERENCE_PROPERTY, reference, true);
    }

    public Reference getReference() {
        return (Reference)readProperty(REFERENCE_PROPERTY);
    }


    public void setReserveCollection(ReserveCollection reserveCollection) {
        setToOneTarget(RESERVE_COLLECTION_PROPERTY, reserveCollection, true);
    }

    public ReserveCollection getReserveCollection() {
        return (ReserveCollection)readProperty(RESERVE_COLLECTION_PROPERTY);
    }


    public void setWebLink(WebLink webLink) {
        setToOneTarget(WEB_LINK_PROPERTY, webLink, true);
    }

    public WebLink getWebLink() {
        return (WebLink)readProperty(WEB_LINK_PROPERTY);
    }


}
