package unidue.rc.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Resource;

/**
 * Class _FileAccess was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FileAccess extends CayenneDataObject {

    public static final String ACCESS_DATE_PROPERTY = "accessDate";
    public static final String REALMHASH_PROPERTY = "realmhash";
    public static final String USERHASH_PROPERTY = "userhash";
    public static final String RESOURCE_PROPERTY = "resource";

    public static final String ID_PK_COLUMN = "id";

    public void setAccessDate(Date accessDate) {
        writeProperty(ACCESS_DATE_PROPERTY, accessDate);
    }
    public Date getAccessDate() {
        return (Date)readProperty(ACCESS_DATE_PROPERTY);
    }

    public void setRealmhash(String realmhash) {
        writeProperty(REALMHASH_PROPERTY, realmhash);
    }
    public String getRealmhash() {
        return (String)readProperty(REALMHASH_PROPERTY);
    }

    public void setUserhash(String userhash) {
        writeProperty(USERHASH_PROPERTY, userhash);
    }
    public String getUserhash() {
        return (String)readProperty(USERHASH_PROPERTY);
    }

    public void setResource(Resource resource) {
        setToOneTarget(RESOURCE_PROPERTY, resource, true);
    }

    public Resource getResource() {
        return (Resource)readProperty(RESOURCE_PROPERTY);
    }


}
