package unidue.rc.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _JobComment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _JobComment extends CayenneDataObject {

    public static final String AUTHOR_ID_PROPERTY = "authorId";
    public static final String COMMENT_PROPERTY = "comment";
    public static final String DATE_PROPERTY = "date";

    public static final String ID_PK_COLUMN = "id";

    public void setAuthorId(Integer authorId) {
        writeProperty(AUTHOR_ID_PROPERTY, authorId);
    }
    public Integer getAuthorId() {
        return (Integer)readProperty(AUTHOR_ID_PROPERTY);
    }

    public void setComment(String comment) {
        writeProperty(COMMENT_PROPERTY, comment);
    }
    public String getComment() {
        return (String)readProperty(COMMENT_PROPERTY);
    }

    public void setDate(Date date) {
        writeProperty(DATE_PROPERTY, date);
    }
    public Date getDate() {
        return (Date)readProperty(DATE_PROPERTY);
    }

}
