package unidue.rc.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Entry;
import unidue.rc.model.Resource;
import unidue.rc.model.ScanJob;

/**
 * Class _JournalArticle was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _JournalArticle extends CayenneDataObject {

    public static final String ARTICLE_TITLE_PROPERTY = "articleTitle";
    public static final String AUTHORS_PROPERTY = "authors";
    public static final String COMMENT_PROPERTY = "comment";
    public static final String ISSN_PROPERTY = "issn";
    public static final String ISSUE_PROPERTY = "issue";
    public static final String JOURNAL_TITLE_PROPERTY = "journalTitle";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String PAGE_END_PROPERTY = "pageEnd";
    public static final String PAGE_START_PROPERTY = "pageStart";
    public static final String PLACE_OF_PUBLICATION_PROPERTY = "placeOfPublication";
    public static final String PUBLISHER_PROPERTY = "publisher";
    public static final String REFERENCE_NUMBER_PROPERTY = "referenceNumber";
    public static final String SIGNATURE_PROPERTY = "signature";
    public static final String TOTAL_PAGES_PROPERTY = "totalPages";
    public static final String VOLUME_PROPERTY = "volume";
    public static final String ENTRY_PROPERTY = "entry";
    public static final String RESOURCE_PROPERTY = "resource";
    public static final String SCAN_JOB_PROPERTY = "scanJob";

    public static final String ID_PK_COLUMN = "id";

    public void setArticleTitle(String articleTitle) {
        writeProperty(ARTICLE_TITLE_PROPERTY, articleTitle);
    }
    public String getArticleTitle() {
        return (String)readProperty(ARTICLE_TITLE_PROPERTY);
    }

    public void setAuthors(String authors) {
        writeProperty(AUTHORS_PROPERTY, authors);
    }
    public String getAuthors() {
        return (String)readProperty(AUTHORS_PROPERTY);
    }

    public void setComment(String comment) {
        writeProperty(COMMENT_PROPERTY, comment);
    }
    public String getComment() {
        return (String)readProperty(COMMENT_PROPERTY);
    }

    public void setIssn(String issn) {
        writeProperty(ISSN_PROPERTY, issn);
    }
    public String getIssn() {
        return (String)readProperty(ISSN_PROPERTY);
    }

    public void setIssue(String issue) {
        writeProperty(ISSUE_PROPERTY, issue);
    }
    public String getIssue() {
        return (String)readProperty(ISSUE_PROPERTY);
    }

    public void setJournalTitle(String journalTitle) {
        writeProperty(JOURNAL_TITLE_PROPERTY, journalTitle);
    }
    public String getJournalTitle() {
        return (String)readProperty(JOURNAL_TITLE_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setPageEnd(String pageEnd) {
        writeProperty(PAGE_END_PROPERTY, pageEnd);
    }
    public String getPageEnd() {
        return (String)readProperty(PAGE_END_PROPERTY);
    }

    public void setPageStart(String pageStart) {
        writeProperty(PAGE_START_PROPERTY, pageStart);
    }
    public String getPageStart() {
        return (String)readProperty(PAGE_START_PROPERTY);
    }

    public void setPlaceOfPublication(String placeOfPublication) {
        writeProperty(PLACE_OF_PUBLICATION_PROPERTY, placeOfPublication);
    }
    public String getPlaceOfPublication() {
        return (String)readProperty(PLACE_OF_PUBLICATION_PROPERTY);
    }

    public void setPublisher(String publisher) {
        writeProperty(PUBLISHER_PROPERTY, publisher);
    }
    public String getPublisher() {
        return (String)readProperty(PUBLISHER_PROPERTY);
    }

    public void setReferenceNumber(String referenceNumber) {
        writeProperty(REFERENCE_NUMBER_PROPERTY, referenceNumber);
    }
    public String getReferenceNumber() {
        return (String)readProperty(REFERENCE_NUMBER_PROPERTY);
    }

    public void setSignature(String signature) {
        writeProperty(SIGNATURE_PROPERTY, signature);
    }
    public String getSignature() {
        return (String)readProperty(SIGNATURE_PROPERTY);
    }

    public void setTotalPages(Integer totalPages) {
        writeProperty(TOTAL_PAGES_PROPERTY, totalPages);
    }
    public Integer getTotalPages() {
        return (Integer)readProperty(TOTAL_PAGES_PROPERTY);
    }

    public void setVolume(String volume) {
        writeProperty(VOLUME_PROPERTY, volume);
    }
    public String getVolume() {
        return (String)readProperty(VOLUME_PROPERTY);
    }

    public void setEntry(Entry entry) {
        setToOneTarget(ENTRY_PROPERTY, entry, true);
    }

    public Entry getEntry() {
        return (Entry)readProperty(ENTRY_PROPERTY);
    }


    public void setResource(Resource resource) {
        setToOneTarget(RESOURCE_PROPERTY, resource, true);
    }

    public Resource getResource() {
        return (Resource)readProperty(RESOURCE_PROPERTY);
    }


    public void setScanJob(ScanJob scanJob) {
        setToOneTarget(SCAN_JOB_PROPERTY, scanJob, true);
    }

    public ScanJob getScanJob() {
        return (ScanJob)readProperty(SCAN_JOB_PROPERTY);
    }


}
