package unidue.rc.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.LibraryLocation;
import unidue.rc.model.ReserveCollection;

/**
 * Class _LibraryLocation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LibraryLocation extends CayenneDataObject {

    public static final String DELETED_PROPERTY = "deleted";
    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String PHYSICAL_PROPERTY = "physical";
    public static final String CHILD_LOCATIONS_PROPERTY = "childLocations";
    public static final String PARENT_LOCATION_PROPERTY = "parentLocation";
    public static final String RESERVE_COLLECTIONS_PROPERTY = "reserveCollections";

    public static final String ID_PK_COLUMN = "id";

    public void setDeleted(boolean deleted) {
        writeProperty(DELETED_PROPERTY, deleted);
    }
	public boolean isDeleted() {
        Boolean value = (Boolean)readProperty(DELETED_PROPERTY);
        return (value != null) ? value.booleanValue() : false;
    }

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setPhysical(boolean physical) {
        writeProperty(PHYSICAL_PROPERTY, physical);
    }
	public boolean isPhysical() {
        Boolean value = (Boolean)readProperty(PHYSICAL_PROPERTY);
        return (value != null) ? value.booleanValue() : false;
    }

    public void addToChildLocations(LibraryLocation obj) {
        addToManyTarget(CHILD_LOCATIONS_PROPERTY, obj, true);
    }
    public void removeFromChildLocations(LibraryLocation obj) {
        removeToManyTarget(CHILD_LOCATIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<LibraryLocation> getChildLocations() {
        return (List<LibraryLocation>)readProperty(CHILD_LOCATIONS_PROPERTY);
    }


    public void setParentLocation(LibraryLocation parentLocation) {
        setToOneTarget(PARENT_LOCATION_PROPERTY, parentLocation, true);
    }

    public LibraryLocation getParentLocation() {
        return (LibraryLocation)readProperty(PARENT_LOCATION_PROPERTY);
    }


    public void addToReserveCollections(ReserveCollection obj) {
        addToManyTarget(RESERVE_COLLECTIONS_PROPERTY, obj, true);
    }
    public void removeFromReserveCollections(ReserveCollection obj) {
        removeToManyTarget(RESERVE_COLLECTIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ReserveCollection> getReserveCollections() {
        return (List<ReserveCollection>)readProperty(RESERVE_COLLECTIONS_PROPERTY);
    }


}
