package unidue.rc.model.auto;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Mail;
import unidue.rc.model.MailNodeType;

/**
 * Class _MailNode was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MailNode extends CayenneDataObject {

    public static final String TYPE_PROPERTY = "type";
    public static final String VALUE_PROPERTY = "value";
    public static final String MAIL_PROPERTY = "mail";

    public static final String ID_PK_COLUMN = "id";

    public void setType(MailNodeType type) {
        writeProperty(TYPE_PROPERTY, type);
    }
    public MailNodeType getType() {
        return (MailNodeType)readProperty(TYPE_PROPERTY);
    }

    public void setValue(String value) {
        writeProperty(VALUE_PROPERTY, value);
    }
    public String getValue() {
        return (String)readProperty(VALUE_PROPERTY);
    }

    public void setMail(Mail mail) {
        setToOneTarget(MAIL_PROPERTY, mail, true);
    }

    public Mail getMail() {
        return (Mail)readProperty(MAIL_PROPERTY);
    }


}
