package unidue.rc.model.auto;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Role;

/**
 * Class _Membership was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Membership extends CayenneDataObject {

    public static final String USER_ID_PROPERTY = "userID";
    public static final String ROLE_PROPERTY = "role";

    public static final String ROLE_ID_PK_COLUMN = "roleId";
    public static final String USER_ID_PK_COLUMN = "userId";

    public void setUserID(Integer userID) {
        writeProperty(USER_ID_PROPERTY, userID);
    }
    public Integer getUserID() {
        return (Integer)readProperty(USER_ID_PROPERTY);
    }

    public void setRole(Role role) {
        setToOneTarget(ROLE_PROPERTY, role, true);
    }

    public Role getRole() {
        return (Role)readProperty(ROLE_PROPERTY);
    }


}
