package unidue.rc.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Mail;
import unidue.rc.model.ReserveCollection;

/**
 * Class _Migration was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Migration extends CayenneDataObject {

    public static final String CODE_USED_DATE_PROPERTY = "codeUsedDate";
    public static final String DOCUMENT_ID_PROPERTY = "documentID";
    public static final String FINISHED_PROPERTY = "finished";
    public static final String MIGRATION_CODE_PROPERTY = "migrationCode";
    public static final String MAILS_PROPERTY = "mails";
    public static final String RESERVE_COLLECTION_PROPERTY = "reserveCollection";

    public static final String ID_PK_COLUMN = "id";

    public void setCodeUsedDate(Date codeUsedDate) {
        writeProperty(CODE_USED_DATE_PROPERTY, codeUsedDate);
    }
    public Date getCodeUsedDate() {
        return (Date)readProperty(CODE_USED_DATE_PROPERTY);
    }

    public void setDocumentID(Integer documentID) {
        writeProperty(DOCUMENT_ID_PROPERTY, documentID);
    }
    public Integer getDocumentID() {
        return (Integer)readProperty(DOCUMENT_ID_PROPERTY);
    }

    public void setFinished(boolean finished) {
        writeProperty(FINISHED_PROPERTY, finished);
    }
	public boolean isFinished() {
        Boolean value = (Boolean)readProperty(FINISHED_PROPERTY);
        return (value != null) ? value.booleanValue() : false;
    }

    public void setMigrationCode(String migrationCode) {
        writeProperty(MIGRATION_CODE_PROPERTY, migrationCode);
    }
    public String getMigrationCode() {
        return (String)readProperty(MIGRATION_CODE_PROPERTY);
    }

    public void addToMails(Mail obj) {
        addToManyTarget(MAILS_PROPERTY, obj, true);
    }
    public void removeFromMails(Mail obj) {
        removeToManyTarget(MAILS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Mail> getMails() {
        return (List<Mail>)readProperty(MAILS_PROPERTY);
    }


    public void setReserveCollection(ReserveCollection reserveCollection) {
        setToOneTarget(RESERVE_COLLECTION_PROPERTY, reserveCollection, true);
    }

    public ReserveCollection getReserveCollection() {
        return (ReserveCollection)readProperty(RESERVE_COLLECTION_PROPERTY);
    }


}
