package unidue.rc.model.auto;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.LibraryLocation;

/**
 * Class _OrderMailRecipient was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OrderMailRecipient extends CayenneDataObject {

    public static final String INSTANCE_CLASS_PROPERTY = "instanceClass";
    public static final String MAIL_PROPERTY = "mail";
    public static final String LOCATION_PROPERTY = "location";

    public static final String ID_PK_COLUMN = "id";

    public void setInstanceClass(String instanceClass) {
        writeProperty(INSTANCE_CLASS_PROPERTY, instanceClass);
    }
    public String getInstanceClass() {
        return (String)readProperty(INSTANCE_CLASS_PROPERTY);
    }

    public void setMail(String mail) {
        writeProperty(MAIL_PROPERTY, mail);
    }
    public String getMail() {
        return (String)readProperty(MAIL_PROPERTY);
    }

    public void setLocation(LibraryLocation location) {
        setToOneTarget(LOCATION_PROPERTY, location, true);
    }

    public LibraryLocation getLocation() {
        return (LibraryLocation)readProperty(LOCATION_PROPERTY);
    }


}
