package unidue.rc.model.auto;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Action;
import unidue.rc.model.Role;

/**
 * Class _PermissionDefinition was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PermissionDefinition extends CayenneDataObject {

    public static final String IS_INSTANCE_BOUND_PROPERTY = "isInstanceBound";
    public static final String ACTION_PROPERTY = "action";
    public static final String ROLE_PROPERTY = "role";

    public static final String ID_PK_COLUMN = "id";

    public void setIsInstanceBound(boolean isInstanceBound) {
        writeProperty(IS_INSTANCE_BOUND_PROPERTY, isInstanceBound);
    }
	public boolean isIsInstanceBound() {
        Boolean value = (Boolean)readProperty(IS_INSTANCE_BOUND_PROPERTY);
        return (value != null) ? value.booleanValue() : false;
    }

    public void setAction(Action action) {
        setToOneTarget(ACTION_PROPERTY, action, true);
    }

    public Action getAction() {
        return (Action)readProperty(ACTION_PROPERTY);
    }


    public void setRole(Role role) {
        setToOneTarget(ROLE_PROPERTY, role, true);
    }

    public Role getRole() {
        return (Role)readProperty(ROLE_PROPERTY);
    }


}
