package unidue.rc.model.auto;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Action;

/**
 * Class _Permission was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Permission extends CayenneDataObject {

    public static final String INSTANCE_CLASS_PROPERTY = "instanceClass";
    public static final String INSTANCE_ID_PROPERTY = "instanceID";
    public static final String USER_ID_PROPERTY = "userID";
    public static final String ACTION_PROPERTY = "action";

    public static final String ID_PK_COLUMN = "id";

    public void setInstanceClass(String instanceClass) {
        writeProperty(INSTANCE_CLASS_PROPERTY, instanceClass);
    }
    public String getInstanceClass() {
        return (String)readProperty(INSTANCE_CLASS_PROPERTY);
    }

    public void setInstanceID(Integer instanceID) {
        writeProperty(INSTANCE_ID_PROPERTY, instanceID);
    }
    public Integer getInstanceID() {
        return (Integer)readProperty(INSTANCE_ID_PROPERTY);
    }

    public void setUserID(Integer userID) {
        writeProperty(USER_ID_PROPERTY, userID);
    }
    public Integer getUserID() {
        return (Integer)readProperty(USER_ID_PROPERTY);
    }

    public void setAction(Action action) {
        setToOneTarget(ACTION_PROPERTY, action, true);
    }

    public Action getAction() {
        return (Action)readProperty(ACTION_PROPERTY);
    }


}
