package unidue.rc.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.ReserveCollection;

/**
 * Class _ReserveCollectionNumber was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ReserveCollectionNumber extends CayenneDataObject {

    public static final String NUMBER_PROPERTY = "number";
    public static final String COLLECTIONS_PROPERTY = "collections";

    public static final String NUMBER_PK_COLUMN = "number";

    public void setNumber(Integer number) {
        writeProperty(NUMBER_PROPERTY, number);
    }
    public Integer getNumber() {
        return (Integer)readProperty(NUMBER_PROPERTY);
    }

    public void addToCollections(ReserveCollection obj) {
        addToManyTarget(COLLECTIONS_PROPERTY, obj, true);
    }
    public void removeFromCollections(ReserveCollection obj) {
        removeToManyTarget(COLLECTIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ReserveCollection> getCollections() {
        return (List<ReserveCollection>)readProperty(COLLECTIONS_PROPERTY);
    }


}
