package unidue.rc.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Entry;
import unidue.rc.model.LibraryLocation;
import unidue.rc.model.Migration;
import unidue.rc.model.Participation;
import unidue.rc.model.ReserveCollectionNumber;
import unidue.rc.model.ReserveCollectionStatus;
import unidue.rc.model.Warning;

/**
 * Class _ReserveCollection was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ReserveCollection extends CayenneDataObject {

    public static final String ALEPH_SYSTEM_ID_PROPERTY = "alephSystemId";
    public static final String ALEPH_USER_ID_PROPERTY = "alephUserId";
    public static final String COMMENT_PROPERTY = "comment";
    public static final String CREATED_PROPERTY = "created";
    public static final String DISSOLVE_AT_PROPERTY = "dissolveAt";
    public static final String ID_PROPERTY = "id";
    public static final String MEDIA_DOWNLOAD_ALLOWED_PROPERTY = "mediaDownloadAllowed";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String ORIGIN_ID_PROPERTY = "originId";
    public static final String PERMALINK_PROPERTY = "permalink";
    public static final String PIWIK_ID_PROPERTY = "piwikId";
    public static final String PROLONG_CODE_PROPERTY = "prolongCode";
    public static final String PROLONG_USED_PROPERTY = "prolongUsed";
    public static final String READ_KEY_PROPERTY = "readKey";
    public static final String STATUS_PROPERTY = "status";
    public static final String TITLE_PROPERTY = "title";
    public static final String VALID_TO_PROPERTY = "validTo";
    public static final String WRITE_KEY_PROPERTY = "writeKey";
    public static final String ENTRIES_PROPERTY = "entries";
    public static final String LIBRARY_LOCATION_PROPERTY = "libraryLocation";
    public static final String MIGRATION_PROPERTY = "migration";
    public static final String NUMBER_PROPERTY = "number";
    public static final String PARTICIPATIONS_PROPERTY = "participations";
    public static final String WARNINGS_PROPERTY = "warnings";

    public static final String ID_PK_COLUMN = "id";

    public void setAlephSystemId(String alephSystemId) {
        writeProperty(ALEPH_SYSTEM_ID_PROPERTY, alephSystemId);
    }
    public String getAlephSystemId() {
        return (String)readProperty(ALEPH_SYSTEM_ID_PROPERTY);
    }

    public void setAlephUserId(String alephUserId) {
        writeProperty(ALEPH_USER_ID_PROPERTY, alephUserId);
    }
    public String getAlephUserId() {
        return (String)readProperty(ALEPH_USER_ID_PROPERTY);
    }

    public void setComment(String comment) {
        writeProperty(COMMENT_PROPERTY, comment);
    }
    public String getComment() {
        return (String)readProperty(COMMENT_PROPERTY);
    }

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setDissolveAt(Date dissolveAt) {
        writeProperty(DISSOLVE_AT_PROPERTY, dissolveAt);
    }
    public Date getDissolveAt() {
        return (Date)readProperty(DISSOLVE_AT_PROPERTY);
    }

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setMediaDownloadAllowed(boolean mediaDownloadAllowed) {
        writeProperty(MEDIA_DOWNLOAD_ALLOWED_PROPERTY, mediaDownloadAllowed);
    }
	public boolean isMediaDownloadAllowed() {
        Boolean value = (Boolean)readProperty(MEDIA_DOWNLOAD_ALLOWED_PROPERTY);
        return (value != null) ? value.booleanValue() : false;
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setOriginId(Integer originId) {
        writeProperty(ORIGIN_ID_PROPERTY, originId);
    }
    public Integer getOriginId() {
        return (Integer)readProperty(ORIGIN_ID_PROPERTY);
    }

    public void setPermalink(String permalink) {
        writeProperty(PERMALINK_PROPERTY, permalink);
    }
    public String getPermalink() {
        return (String)readProperty(PERMALINK_PROPERTY);
    }

    public void setPiwikId(Integer piwikId) {
        writeProperty(PIWIK_ID_PROPERTY, piwikId);
    }
    public Integer getPiwikId() {
        return (Integer)readProperty(PIWIK_ID_PROPERTY);
    }

    public void setProlongCode(String prolongCode) {
        writeProperty(PROLONG_CODE_PROPERTY, prolongCode);
    }
    public String getProlongCode() {
        return (String)readProperty(PROLONG_CODE_PROPERTY);
    }

    public void setProlongUsed(Date prolongUsed) {
        writeProperty(PROLONG_USED_PROPERTY, prolongUsed);
    }
    public Date getProlongUsed() {
        return (Date)readProperty(PROLONG_USED_PROPERTY);
    }

    public void setReadKey(String readKey) {
        writeProperty(READ_KEY_PROPERTY, readKey);
    }
    public String getReadKey() {
        return (String)readProperty(READ_KEY_PROPERTY);
    }

    public void setStatus(ReserveCollectionStatus status) {
        writeProperty(STATUS_PROPERTY, status);
    }
    public ReserveCollectionStatus getStatus() {
        return (ReserveCollectionStatus)readProperty(STATUS_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void setValidTo(Date validTo) {
        writeProperty(VALID_TO_PROPERTY, validTo);
    }
    public Date getValidTo() {
        return (Date)readProperty(VALID_TO_PROPERTY);
    }

    public void setWriteKey(String writeKey) {
        writeProperty(WRITE_KEY_PROPERTY, writeKey);
    }
    public String getWriteKey() {
        return (String)readProperty(WRITE_KEY_PROPERTY);
    }

    public void addToEntries(Entry obj) {
        addToManyTarget(ENTRIES_PROPERTY, obj, true);
    }
    public void removeFromEntries(Entry obj) {
        removeToManyTarget(ENTRIES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Entry> getEntries() {
        return (List<Entry>)readProperty(ENTRIES_PROPERTY);
    }


    public void setLibraryLocation(LibraryLocation libraryLocation) {
        setToOneTarget(LIBRARY_LOCATION_PROPERTY, libraryLocation, true);
    }

    public LibraryLocation getLibraryLocation() {
        return (LibraryLocation)readProperty(LIBRARY_LOCATION_PROPERTY);
    }


    public void setMigration(Migration migration) {
        setToOneTarget(MIGRATION_PROPERTY, migration, true);
    }

    public Migration getMigration() {
        return (Migration)readProperty(MIGRATION_PROPERTY);
    }


    public void setNumber(ReserveCollectionNumber number) {
        setToOneTarget(NUMBER_PROPERTY, number, true);
    }

    public ReserveCollectionNumber getNumber() {
        return (ReserveCollectionNumber)readProperty(NUMBER_PROPERTY);
    }


    public void addToParticipations(Participation obj) {
        addToManyTarget(PARTICIPATIONS_PROPERTY, obj, true);
    }
    public void removeFromParticipations(Participation obj) {
        removeToManyTarget(PARTICIPATIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Participation> getParticipations() {
        return (List<Participation>)readProperty(PARTICIPATIONS_PROPERTY);
    }


    public void addToWarnings(Warning obj) {
        addToManyTarget(WARNINGS_PROPERTY, obj, true);
    }
    public void removeFromWarnings(Warning obj) {
        removeToManyTarget(WARNINGS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Warning> getWarnings() {
        return (List<Warning>)readProperty(WARNINGS_PROPERTY);
    }


}
