package unidue.rc.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Book;
import unidue.rc.model.BookChapter;
import unidue.rc.model.CopyrightReviewStatus;
import unidue.rc.model.File;
import unidue.rc.model.FileAccess;
import unidue.rc.model.JournalArticle;
import unidue.rc.model.Reference;

/**
 * Class _Resource was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Resource extends CayenneDataObject {

    public static final String COPYRIGHT_REVIEW_STATUS_PROPERTY = "copyrightReviewStatus";
    public static final String FILE_DELETED_PROPERTY = "fileDeleted";
    public static final String FILE_PATH_PROPERTY = "filePath";
    public static final String FULL_TEXT_URL_PROPERTY = "fullTextURL";
    public static final String MIME_TYPE_PROPERTY = "mimeType";
    public static final String BOOK_PROPERTY = "book";
    public static final String BOOK_CHAPTER_PROPERTY = "bookChapter";
    public static final String FILE_PROPERTY = "file";
    public static final String FILE_ACCESS_PROPERTY = "fileAccess";
    public static final String JOURNAL_ARTICLE_PROPERTY = "journalArticle";
    public static final String REFERENCE_PROPERTY = "reference";

    public static final String ID_PK_COLUMN = "id";

    public void setCopyrightReviewStatus(CopyrightReviewStatus copyrightReviewStatus) {
        writeProperty(COPYRIGHT_REVIEW_STATUS_PROPERTY, copyrightReviewStatus);
    }
    public CopyrightReviewStatus getCopyrightReviewStatus() {
        return (CopyrightReviewStatus)readProperty(COPYRIGHT_REVIEW_STATUS_PROPERTY);
    }

    public void setFileDeleted(Date fileDeleted) {
        writeProperty(FILE_DELETED_PROPERTY, fileDeleted);
    }
    public Date getFileDeleted() {
        return (Date)readProperty(FILE_DELETED_PROPERTY);
    }

    public void setFilePath(String filePath) {
        writeProperty(FILE_PATH_PROPERTY, filePath);
    }
    public String getFilePath() {
        return (String)readProperty(FILE_PATH_PROPERTY);
    }

    public void setFullTextURL(String fullTextURL) {
        writeProperty(FULL_TEXT_URL_PROPERTY, fullTextURL);
    }
    public String getFullTextURL() {
        return (String)readProperty(FULL_TEXT_URL_PROPERTY);
    }

    public void setMimeType(String mimeType) {
        writeProperty(MIME_TYPE_PROPERTY, mimeType);
    }
    public String getMimeType() {
        return (String)readProperty(MIME_TYPE_PROPERTY);
    }

    public void setBook(Book book) {
        setToOneTarget(BOOK_PROPERTY, book, true);
    }

    public Book getBook() {
        return (Book)readProperty(BOOK_PROPERTY);
    }


    public void setBookChapter(BookChapter bookChapter) {
        setToOneTarget(BOOK_CHAPTER_PROPERTY, bookChapter, true);
    }

    public BookChapter getBookChapter() {
        return (BookChapter)readProperty(BOOK_CHAPTER_PROPERTY);
    }


    public void setFile(File file) {
        setToOneTarget(FILE_PROPERTY, file, true);
    }

    public File getFile() {
        return (File)readProperty(FILE_PROPERTY);
    }


    public void addToFileAccess(FileAccess obj) {
        addToManyTarget(FILE_ACCESS_PROPERTY, obj, true);
    }
    public void removeFromFileAccess(FileAccess obj) {
        removeToManyTarget(FILE_ACCESS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FileAccess> getFileAccess() {
        return (List<FileAccess>)readProperty(FILE_ACCESS_PROPERTY);
    }


    public void setJournalArticle(JournalArticle journalArticle) {
        setToOneTarget(JOURNAL_ARTICLE_PROPERTY, journalArticle, true);
    }

    public JournalArticle getJournalArticle() {
        return (JournalArticle)readProperty(JOURNAL_ARTICLE_PROPERTY);
    }


    public void setReference(Reference reference) {
        setToOneTarget(REFERENCE_PROPERTY, reference, true);
    }

    public Reference getReference() {
        return (Reference)readProperty(REFERENCE_PROPERTY);
    }


}
