package unidue.rc.model.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.BookChapter;
import unidue.rc.model.JobComment;
import unidue.rc.model.JournalArticle;
import unidue.rc.model.LibraryLocation;
import unidue.rc.model.ScanJobStatus;

/**
 * Class _ScanJob was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ScanJob extends CayenneDataObject {

    public static final String MODIFIED_PROPERTY = "modified";
    public static final String STATUS_PROPERTY = "status";
    public static final String BOOK_CHAPTER_PROPERTY = "bookChapter";
    public static final String COMMENTS_PROPERTY = "comments";
    public static final String JOURNAL_ARTICLE_PROPERTY = "journalArticle";
    public static final String LOCATION_PROPERTY = "location";

    public static final String ID_PK_COLUMN = "id";

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setStatus(ScanJobStatus status) {
        writeProperty(STATUS_PROPERTY, status);
    }
    public ScanJobStatus getStatus() {
        return (ScanJobStatus)readProperty(STATUS_PROPERTY);
    }

    public void setBookChapter(BookChapter bookChapter) {
        setToOneTarget(BOOK_CHAPTER_PROPERTY, bookChapter, true);
    }

    public BookChapter getBookChapter() {
        return (BookChapter)readProperty(BOOK_CHAPTER_PROPERTY);
    }


    public void addToComments(JobComment obj) {
        addToManyTarget(COMMENTS_PROPERTY, obj, true);
    }
    public void removeFromComments(JobComment obj) {
        removeToManyTarget(COMMENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<JobComment> getComments() {
        return (List<JobComment>)readProperty(COMMENTS_PROPERTY);
    }


    public void setJournalArticle(JournalArticle journalArticle) {
        setToOneTarget(JOURNAL_ARTICLE_PROPERTY, journalArticle, true);
    }

    public JournalArticle getJournalArticle() {
        return (JournalArticle)readProperty(JOURNAL_ARTICLE_PROPERTY);
    }


    public void setLocation(LibraryLocation location) {
        setToOneTarget(LOCATION_PROPERTY, location, true);
    }

    public LibraryLocation getLocation() {
        return (LibraryLocation)readProperty(LOCATION_PROPERTY);
    }


}
