package unidue.rc.model.auto;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.SettingType;

/**
 * Class _Setting was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Setting extends CayenneDataObject {

    public static final String FORMAT_PROPERTY = "format";
    public static final String KEY_PROPERTY = "key";
    public static final String LABEL_PROPERTY = "label";
    public static final String TYPE_PROPERTY = "type";
    public static final String VALUE_PROPERTY = "value";

    public static final String KEY_PK_COLUMN = "key";

    public void setFormat(String format) {
        writeProperty(FORMAT_PROPERTY, format);
    }
    public String getFormat() {
        return (String)readProperty(FORMAT_PROPERTY);
    }

    public void setKey(String key) {
        writeProperty(KEY_PROPERTY, key);
    }
    public String getKey() {
        return (String)readProperty(KEY_PROPERTY);
    }

    public void setLabel(String label) {
        writeProperty(LABEL_PROPERTY, label);
    }
    public String getLabel() {
        return (String)readProperty(LABEL_PROPERTY);
    }

    public void setType(SettingType type) {
        writeProperty(TYPE_PROPERTY, type);
    }
    public SettingType getType() {
        return (SettingType)readProperty(TYPE_PROPERTY);
    }

    public void setValue(String value) {
        writeProperty(VALUE_PROPERTY, value);
    }
    public String getValue() {
        return (String)readProperty(VALUE_PROPERTY);
    }

}
