package unidue.rc.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Statistic was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Statistic extends CayenneDataObject {

    public static final String ARTICLE_COUNT_PROPERTY = "articleCount";
    public static final String BOOK_COUNT_PROPERTY = "bookCount";
    public static final String CHAPTER_COUNT_PROPERTY = "chapterCount";
    public static final String DATE_PROPERTY = "date";
    public static final String ENTRY_COUNT_PROPERTY = "entryCount";
    public static final String FILE_COUNT_PROPERTY = "fileCount";
    public static final String HEADLINE_COUNT_PROPERTY = "headlineCount";
    public static final String HTML_COUNT_PROPERTY = "htmlCount";
    public static final String RESERVECOLLECTION_COUNT_PROPERTY = "reservecollectionCount";
    public static final String TOTAL_FILES_COUNT_PROPERTY = "totalFilesCount";
    public static final String WEBLINK_COUNT_PROPERTY = "weblinkCount";

    public static final String ID_PK_COLUMN = "id";

    public void setArticleCount(Integer articleCount) {
        writeProperty(ARTICLE_COUNT_PROPERTY, articleCount);
    }
    public Integer getArticleCount() {
        return (Integer)readProperty(ARTICLE_COUNT_PROPERTY);
    }

    public void setBookCount(Integer bookCount) {
        writeProperty(BOOK_COUNT_PROPERTY, bookCount);
    }
    public Integer getBookCount() {
        return (Integer)readProperty(BOOK_COUNT_PROPERTY);
    }

    public void setChapterCount(Integer chapterCount) {
        writeProperty(CHAPTER_COUNT_PROPERTY, chapterCount);
    }
    public Integer getChapterCount() {
        return (Integer)readProperty(CHAPTER_COUNT_PROPERTY);
    }

    public void setDate(String date) {
        writeProperty(DATE_PROPERTY, date);
    }
    public String getDate() {
        return (String)readProperty(DATE_PROPERTY);
    }

    public void setEntryCount(Integer entryCount) {
        writeProperty(ENTRY_COUNT_PROPERTY, entryCount);
    }
    public Integer getEntryCount() {
        return (Integer)readProperty(ENTRY_COUNT_PROPERTY);
    }

    public void setFileCount(Integer fileCount) {
        writeProperty(FILE_COUNT_PROPERTY, fileCount);
    }
    public Integer getFileCount() {
        return (Integer)readProperty(FILE_COUNT_PROPERTY);
    }

    public void setHeadlineCount(Integer headlineCount) {
        writeProperty(HEADLINE_COUNT_PROPERTY, headlineCount);
    }
    public Integer getHeadlineCount() {
        return (Integer)readProperty(HEADLINE_COUNT_PROPERTY);
    }

    public void setHtmlCount(Integer htmlCount) {
        writeProperty(HTML_COUNT_PROPERTY, htmlCount);
    }
    public Integer getHtmlCount() {
        return (Integer)readProperty(HTML_COUNT_PROPERTY);
    }

    public void setReservecollectionCount(Integer reservecollectionCount) {
        writeProperty(RESERVECOLLECTION_COUNT_PROPERTY, reservecollectionCount);
    }
    public Integer getReservecollectionCount() {
        return (Integer)readProperty(RESERVECOLLECTION_COUNT_PROPERTY);
    }

    public void setTotalFilesCount(Integer totalFilesCount) {
        writeProperty(TOTAL_FILES_COUNT_PROPERTY, totalFilesCount);
    }
    public Integer getTotalFilesCount() {
        return (Integer)readProperty(TOTAL_FILES_COUNT_PROPERTY);
    }

    public void setWeblinkCount(Integer weblinkCount) {
        writeProperty(WEBLINK_COUNT_PROPERTY, weblinkCount);
    }
    public Integer getWeblinkCount() {
        return (Integer)readProperty(WEBLINK_COUNT_PROPERTY);
    }

}
