package unidue.rc.model.auto;

import org.apache.cayenne.CayenneDataObject;

import unidue.rc.model.Entry;

/**
 * Class _WebLink was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebLink extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String URL_PROPERTY = "url";
    public static final String ENTRY_PROPERTY = "entry";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setUrl(String url) {
        writeProperty(URL_PROPERTY, url);
    }
    public String getUrl() {
        return (String)readProperty(URL_PROPERTY);
    }

    public void setEntry(Entry entry) {
        setToOneTarget(ENTRY_PROPERTY, entry, true);
    }

    public Entry getEntry() {
        return (Entry)readProperty(ENTRY_PROPERTY);
    }


}
