package unidue.rc.model.accesslog.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Access was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Access extends CayenneDataObject {

    public static final String BYTES_PROPERTY = "bytes";
    public static final String METHOD_PROPERTY = "method";
    public static final String QUERY_PROPERTY = "query";
    public static final String REFERER_PROPERTY = "referer";
    public static final String REMOTE_HOST_PROPERTY = "remoteHost";
    public static final String REQUEST_URI_PROPERTY = "requestURI";
    public static final String STATUS_PROPERTY = "status";
    public static final String TIMESTAMP_PROPERTY = "timestamp";
    public static final String USER_AGENT_PROPERTY = "userAgent";
    public static final String USERNAME_PROPERTY = "username";
    public static final String VIRTUAL_HOST_PROPERTY = "virtualHost";

    public static final String ID_PK_COLUMN = "id";

    public void setBytes(Integer bytes) {
        writeProperty(BYTES_PROPERTY, bytes);
    }
    public Integer getBytes() {
        return (Integer)readProperty(BYTES_PROPERTY);
    }

    public void setMethod(String method) {
        writeProperty(METHOD_PROPERTY, method);
    }
    public String getMethod() {
        return (String)readProperty(METHOD_PROPERTY);
    }

    public void setQuery(String query) {
        writeProperty(QUERY_PROPERTY, query);
    }
    public String getQuery() {
        return (String)readProperty(QUERY_PROPERTY);
    }

    public void setReferer(String referer) {
        writeProperty(REFERER_PROPERTY, referer);
    }
    public String getReferer() {
        return (String)readProperty(REFERER_PROPERTY);
    }

    public void setRemoteHost(String remoteHost) {
        writeProperty(REMOTE_HOST_PROPERTY, remoteHost);
    }
    public String getRemoteHost() {
        return (String)readProperty(REMOTE_HOST_PROPERTY);
    }

    public void setRequestURI(String requestURI) {
        writeProperty(REQUEST_URI_PROPERTY, requestURI);
    }
    public String getRequestURI() {
        return (String)readProperty(REQUEST_URI_PROPERTY);
    }

    public void setStatus(Short status) {
        writeProperty(STATUS_PROPERTY, status);
    }
    public Short getStatus() {
        return (Short)readProperty(STATUS_PROPERTY);
    }

    public void setTimestamp(Date timestamp) {
        writeProperty(TIMESTAMP_PROPERTY, timestamp);
    }
    public Date getTimestamp() {
        return (Date)readProperty(TIMESTAMP_PROPERTY);
    }

    public void setUserAgent(String userAgent) {
        writeProperty(USER_AGENT_PROPERTY, userAgent);
    }
    public String getUserAgent() {
        return (String)readProperty(USER_AGENT_PROPERTY);
    }

    public void setUsername(String username) {
        writeProperty(USERNAME_PROPERTY, username);
    }
    public String getUsername() {
        return (String)readProperty(USERNAME_PROPERTY);
    }

    public void setVirtualHost(String virtualHost) {
        writeProperty(VIRTUAL_HOST_PROPERTY, virtualHost);
    }
    public String getVirtualHost() {
        return (String)readProperty(VIRTUAL_HOST_PROPERTY);
    }

}
