package miless.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Derivates was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Derivates extends CayenneDataObject {

    public static final String CREATED_PROPERTY = "created";
    public static final String CTS_PROPERTY = "cts";
    public static final String DOC_ID_PROPERTY = "docId";
    public static final String LOCATOR_PROPERTY = "locator";
    public static final String MAIN_FILE_PROPERTY = "mainFile";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String NUM_FILES_PROPERTY = "numFiles";
    public static final String ORIGINAL_PROPERTY = "original";
    public static final String SIZE_PROPERTY = "size";
    public static final String TYPE_PROPERTY = "type";

    public static final String ID_PK_COLUMN = "id";

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setCts(String cts) {
        writeProperty(CTS_PROPERTY, cts);
    }
    public String getCts() {
        return (String)readProperty(CTS_PROPERTY);
    }

    public void setDocId(Integer docId) {
        writeProperty(DOC_ID_PROPERTY, docId);
    }
    public Integer getDocId() {
        return (Integer)readProperty(DOC_ID_PROPERTY);
    }

    public void setLocator(String locator) {
        writeProperty(LOCATOR_PROPERTY, locator);
    }
    public String getLocator() {
        return (String)readProperty(LOCATOR_PROPERTY);
    }

    public void setMainFile(String mainFile) {
        writeProperty(MAIN_FILE_PROPERTY, mainFile);
    }
    public String getMainFile() {
        return (String)readProperty(MAIN_FILE_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setNumFiles(Integer numFiles) {
        writeProperty(NUM_FILES_PROPERTY, numFiles);
    }
    public Integer getNumFiles() {
        return (Integer)readProperty(NUM_FILES_PROPERTY);
    }

    public void setOriginal(Integer original) {
        writeProperty(ORIGINAL_PROPERTY, original);
    }
    public Integer getOriginal() {
        return (Integer)readProperty(ORIGINAL_PROPERTY);
    }

    public void setSize(Long size) {
        writeProperty(SIZE_PROPERTY, size);
    }
    public Long getSize() {
        return (Long)readProperty(SIZE_PROPERTY);
    }

    public void setType(String type) {
        writeProperty(TYPE_PROPERTY, type);
    }
    public String getType() {
        return (String)readProperty(TYPE_PROPERTY);
    }

}
