package miless.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Files was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Files extends CayenneDataObject {

    public static final String CHECKSUM_PROPERTY = "checksum";
    public static final String COPYRIGHT_REVIEW_STATUS_PROPERTY = "copyrightReviewStatus";
    public static final String CT_PROPERTY = "ct";
    public static final String DELETED_PROPERTY = "deleted";
    public static final String ID_PROPERTY = "id";
    public static final String MODIFIED_PROPERTY = "modified";
    public static final String PATH_PROPERTY = "path";
    public static final String SIZE_PROPERTY = "size";
    public static final String STORAGEID_PROPERTY = "storageid";
    public static final String STOREID_PROPERTY = "storeid";

    public static final String FILE_ID_PK_COLUMN = "file_id";

    public void setChecksum(String checksum) {
        writeProperty(CHECKSUM_PROPERTY, checksum);
    }
    public String getChecksum() {
        return (String)readProperty(CHECKSUM_PROPERTY);
    }

    public void setCopyrightReviewStatus(String copyrightReviewStatus) {
        writeProperty(COPYRIGHT_REVIEW_STATUS_PROPERTY, copyrightReviewStatus);
    }
    public String getCopyrightReviewStatus() {
        return (String)readProperty(COPYRIGHT_REVIEW_STATUS_PROPERTY);
    }

    public void setCt(String ct) {
        writeProperty(CT_PROPERTY, ct);
    }
    public String getCt() {
        return (String)readProperty(CT_PROPERTY);
    }

    public void setDeleted(boolean deleted) {
        writeProperty(DELETED_PROPERTY, deleted);
    }
	public boolean isDeleted() {
        Boolean value = (Boolean)readProperty(DELETED_PROPERTY);
        return (value != null) ? value.booleanValue() : false;
    }

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setModified(Date modified) {
        writeProperty(MODIFIED_PROPERTY, modified);
    }
    public Date getModified() {
        return (Date)readProperty(MODIFIED_PROPERTY);
    }

    public void setPath(String path) {
        writeProperty(PATH_PROPERTY, path);
    }
    public String getPath() {
        return (String)readProperty(PATH_PROPERTY);
    }

    public void setSize(Long size) {
        writeProperty(SIZE_PROPERTY, size);
    }
    public Long getSize() {
        return (Long)readProperty(SIZE_PROPERTY);
    }

    public void setStorageid(String storageid) {
        writeProperty(STORAGEID_PROPERTY, storageid);
    }
    public String getStorageid() {
        return (String)readProperty(STORAGEID_PROPERTY);
    }

    public void setStoreid(String storeid) {
        writeProperty(STOREID_PROPERTY, storeid);
    }
    public String getStoreid() {
        return (String)readProperty(STOREID_PROPERTY);
    }

}
