package miless.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import miless.model.MCRCategory;
import miless.model.MCRCategoryLabel;

/**
 * Class _MCRCategory was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MCRCategory extends CayenneDataObject {

    public static final String CATEGID_PROPERTY = "categid";
    public static final String CLASSID_PROPERTY = "classid";
    public static final String INTERNAL_ID_PROPERTY = "internalId";
    public static final String LEFTVALUE_PROPERTY = "leftvalue";
    public static final String LEVEL_PROPERTY = "level";
    public static final String POSITIONINPARENT_PROPERTY = "positioninparent";
    public static final String RIGHTVALUE_PROPERTY = "rightvalue";
    public static final String URI_PROPERTY = "uri";
    public static final String CHILD_CATEGORIES_PROPERTY = "childCategories";
    public static final String LABELS_PROPERTY = "labels";
    public static final String PARENT_CATEGORY_PROPERTY = "parentCategory";

    public static final String INTERNALID_PK_COLUMN = "INTERNALID";

    public void setCategid(String categid) {
        writeProperty(CATEGID_PROPERTY, categid);
    }
    public String getCategid() {
        return (String)readProperty(CATEGID_PROPERTY);
    }

    public void setClassid(String classid) {
        writeProperty(CLASSID_PROPERTY, classid);
    }
    public String getClassid() {
        return (String)readProperty(CLASSID_PROPERTY);
    }

    public void setInternalId(Integer internalId) {
        writeProperty(INTERNAL_ID_PROPERTY, internalId);
    }
    public Integer getInternalId() {
        return (Integer)readProperty(INTERNAL_ID_PROPERTY);
    }

    public void setLeftvalue(Integer leftvalue) {
        writeProperty(LEFTVALUE_PROPERTY, leftvalue);
    }
    public Integer getLeftvalue() {
        return (Integer)readProperty(LEFTVALUE_PROPERTY);
    }

    public void setLevel(Integer level) {
        writeProperty(LEVEL_PROPERTY, level);
    }
    public Integer getLevel() {
        return (Integer)readProperty(LEVEL_PROPERTY);
    }

    public void setPositioninparent(Integer positioninparent) {
        writeProperty(POSITIONINPARENT_PROPERTY, positioninparent);
    }
    public Integer getPositioninparent() {
        return (Integer)readProperty(POSITIONINPARENT_PROPERTY);
    }

    public void setRightvalue(Integer rightvalue) {
        writeProperty(RIGHTVALUE_PROPERTY, rightvalue);
    }
    public Integer getRightvalue() {
        return (Integer)readProperty(RIGHTVALUE_PROPERTY);
    }

    public void setUri(String uri) {
        writeProperty(URI_PROPERTY, uri);
    }
    public String getUri() {
        return (String)readProperty(URI_PROPERTY);
    }

    public void addToChildCategories(MCRCategory obj) {
        addToManyTarget(CHILD_CATEGORIES_PROPERTY, obj, true);
    }
    public void removeFromChildCategories(MCRCategory obj) {
        removeToManyTarget(CHILD_CATEGORIES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MCRCategory> getChildCategories() {
        return (List<MCRCategory>)readProperty(CHILD_CATEGORIES_PROPERTY);
    }


    public void addToLabels(MCRCategoryLabel obj) {
        addToManyTarget(LABELS_PROPERTY, obj, true);
    }
    public void removeFromLabels(MCRCategoryLabel obj) {
        removeToManyTarget(LABELS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MCRCategoryLabel> getLabels() {
        return (List<MCRCategoryLabel>)readProperty(LABELS_PROPERTY);
    }


    public void setParentCategory(MCRCategory parentCategory) {
        setToOneTarget(PARENT_CATEGORY_PROPERTY, parentCategory, true);
    }

    public MCRCategory getParentCategory() {
        return (MCRCategory)readProperty(PARENT_CATEGORY_PROPERTY);
    }


}
