package miless.model.auto;



/**
 * This class was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public class _MilessDatamap {

    public static final String SELECT_MAX_USERID_QUERYNAME = "select_max_userid";
}