package miless.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Permissions was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Permissions extends CayenneDataObject {

    public static final String ACTION_PROPERTY = "action";
    public static final String SID_PROPERTY = "sid";
    public static final String STYPE_PROPERTY = "stype";
    public static final String TID_PROPERTY = "tid";
    public static final String TTYPE_PROPERTY = "ttype";

    public static final String ID_PK_COLUMN = "id";

    public void setAction(String action) {
        writeProperty(ACTION_PROPERTY, action);
    }
    public String getAction() {
        return (String)readProperty(ACTION_PROPERTY);
    }

    public void setSid(Integer sid) {
        writeProperty(SID_PROPERTY, sid);
    }
    public Integer getSid() {
        return (Integer)readProperty(SID_PROPERTY);
    }

    public void setStype(String stype) {
        writeProperty(STYPE_PROPERTY, stype);
    }
    public String getStype() {
        return (String)readProperty(STYPE_PROPERTY);
    }

    public void setTid(Integer tid) {
        writeProperty(TID_PROPERTY, tid);
    }
    public Integer getTid() {
        return (Integer)readProperty(TID_PROPERTY);
    }

    public void setTtype(String ttype) {
        writeProperty(TTYPE_PROPERTY, ttype);
    }
    public String getTtype() {
        return (String)readProperty(TTYPE_PROPERTY);
    }

}
