package miless.model.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    public static final String EMAIL_PROPERTY = "email";
    public static final String HINT_PROPERTY = "hint";
    public static final String IS_TRACKING_ALLOWED_PROPERTY = "isTrackingAllowed";
    public static final String LASTLOGIN_PROPERTY = "lastlogin";
    public static final String LEID_PROPERTY = "leid";
    public static final String ORIGIN_PROPERTY = "origin";
    public static final String OWNERID_PROPERTY = "ownerid";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String REALM_PROPERTY = "realm";
    public static final String REALNAME_PROPERTY = "realname";
    public static final String USERID_PROPERTY = "userid";
    public static final String USERNAME_PROPERTY = "username";

    public static final String USERID_PK_COLUMN = "USERID";

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }
    public String getEmail() {
        return (String)readProperty(EMAIL_PROPERTY);
    }

    public void setHint(String hint) {
        writeProperty(HINT_PROPERTY, hint);
    }
    public String getHint() {
        return (String)readProperty(HINT_PROPERTY);
    }

    public void setIsTrackingAllowed(Boolean isTrackingAllowed) {
        writeProperty(IS_TRACKING_ALLOWED_PROPERTY, isTrackingAllowed);
    }
    public Boolean getIsTrackingAllowed() {
        return (Boolean)readProperty(IS_TRACKING_ALLOWED_PROPERTY);
    }

    public void setLastlogin(Date lastlogin) {
        writeProperty(LASTLOGIN_PROPERTY, lastlogin);
    }
    public Date getLastlogin() {
        return (Date)readProperty(LASTLOGIN_PROPERTY);
    }

    public void setLeid(int leid) {
        writeProperty(LEID_PROPERTY, leid);
    }
    public int getLeid() {
        Object value = readProperty(LEID_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setOrigin(String origin) {
        writeProperty(ORIGIN_PROPERTY, origin);
    }
    public String getOrigin() {
        return (String)readProperty(ORIGIN_PROPERTY);
    }

    public void setOwnerid(int ownerid) {
        writeProperty(OWNERID_PROPERTY, ownerid);
    }
    public int getOwnerid() {
        Object value = readProperty(OWNERID_PROPERTY);
        return (value != null) ? (Integer) value : 0;
    }

    public void setPassword(String password) {
        writeProperty(PASSWORD_PROPERTY, password);
    }
    public String getPassword() {
        return (String)readProperty(PASSWORD_PROPERTY);
    }

    public void setRealm(String realm) {
        writeProperty(REALM_PROPERTY, realm);
    }
    public String getRealm() {
        return (String)readProperty(REALM_PROPERTY);
    }

    public void setRealname(String realname) {
        writeProperty(REALNAME_PROPERTY, realname);
    }
    public String getRealname() {
        return (String)readProperty(REALNAME_PROPERTY);
    }

    public void setUserid(Integer userid) {
        writeProperty(USERID_PROPERTY, userid);
    }
    public Integer getUserid() {
        return (Integer)readProperty(USERID_PROPERTY);
    }

    public void setUsername(String username) {
        writeProperty(USERNAME_PROPERTY, username);
    }
    public String getUsername() {
        return (String)readProperty(USERNAME_PROPERTY);
    }

}
